name:                testdb
version:             0.1.0.0
github:              "githubuser/testdb"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/testdb#readme>

dependencies:
- base >= 4.7 && < 5
- postgresql-simple
- wai
- warp
- bytestring
- text
- aeson
- http-client
- time
- http-types
- wai-extra
- configurator
- directory
- resource-pool
- hspec
- postgresql-simple-migration
- mtl

library:
  source-dirs: src
  # dependencies:
  #  - base64-bytestring
  #  - postgresql-simple
  #  - wai
  #  - warp
  #  - bytestring
   # - text
  #  - aeson
  #  - http-client
  #  - time
  #  - http-types
  #  - wai-extra
  #  - configurator
  #  - directory
  #  - resource-pool
  # exposed-modules:  Lib
executables:
  testdb-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - testdb

tests:
  testdb-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  #  - -Wall
  #  - -Werror
    dependencies:
    - testdb
    - hspec-wai
